/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAlertsRouteImport } from './routes/_shell.alerts'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellArchitectureRouteImport } from './routes/_shell.architecture'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellFraudsRouteImport } from './routes/_shell.frauds'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTransactionsRouteImport } from './routes/_shell.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAlertsRoute = ShellAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellArchitectureRoute = ShellArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFraudsRoute = ShellFraudsRouteImport.update({
  id: '/frauds',
  path: '/frauds',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof ShellAlertsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/architecture': typeof ShellArchitectureRoute
  '/dashboard': typeof ShellDashboardRoute
  '/frauds': typeof ShellFraudsRoute
  '/settings': typeof ShellSettingsRoute
  '/transactions': typeof ShellTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof ShellAlertsRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/architecture': typeof ShellArchitectureRoute
  '/dashboard': typeof ShellDashboardRoute
  '/frauds': typeof ShellFraudsRoute
  '/settings': typeof ShellSettingsRoute
  '/transactions': typeof ShellTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/alerts': typeof ShellAlertsRoute
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/architecture': typeof ShellArchitectureRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/frauds': typeof ShellFraudsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/dashboard'
    | '/frauds'
    | '/settings'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/dashboard'
    | '/frauds'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/alerts'
    | '/_shell/analytics'
    | '/_shell/architecture'
    | '/_shell/dashboard'
    | '/_shell/frauds'
    | '/_shell/settings'
    | '/_shell/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/alerts': {
      id: '/_shell/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof ShellAlertsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/architecture': {
      id: '/_shell/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ShellArchitectureRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/frauds': {
      id: '/_shell/frauds'
      path: '/frauds'
      fullPath: '/frauds'
      preLoaderRoute: typeof ShellFraudsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAlertsRoute: typeof ShellAlertsRoute
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellArchitectureRoute: typeof ShellArchitectureRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellFraudsRoute: typeof ShellFraudsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTransactionsRoute: typeof ShellTransactionsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAlertsRoute: ShellAlertsRoute,
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellArchitectureRoute: ShellArchitectureRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellFraudsRoute: ShellFraudsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTransactionsRoute: ShellTransactionsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
