version: '3.8'

services:
  fraud-db:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: nova_user
      MONGO_INITDB_ROOT_PASSWORD: nova_password
      MONGO_INITDB_DATABASE: nova_fraud
    ports:
      - "27017:27017"
    volumes:
      - fraud_db_data:/data/db

volumes:
  fraud_db_data:
